# .github/workflows/build-deploy-workflow.yml
name: Build And Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v5  
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 

      - name: Init Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: infra

      - name: Apply Terraform
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: infra
